// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrevisaoDoTempoAPI.Data;

#nullable disable

namespace PrevisaoDoTempoAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230724203600_CriandoBD")]
    partial class CriandoBD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PrevisaoDoTempoAPI.Models.Chave", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_expiracao");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("texto");

                    b.Property<uint>("UsuarioId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("Texto")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("tb_chaves");
                });

            modelBuilder.Entity("PrevisaoDoTempoAPI.Models.Consulta", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("cep");

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_consulta");

                    b.Property<uint>("UsuarioId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("tb_consultas");
                });

            modelBuilder.Entity("PrevisaoDoTempoAPI.Models.Usuario", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("login");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("senha");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("tb_usuarios");
                });

            modelBuilder.Entity("PrevisaoDoTempoAPI.Models.Chave", b =>
                {
                    b.HasOne("PrevisaoDoTempoAPI.Models.Usuario", "Usuario")
                        .WithMany("Chaves")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PrevisaoDoTempoAPI.Models.Consulta", b =>
                {
                    b.HasOne("PrevisaoDoTempoAPI.Models.Usuario", "Usuario")
                        .WithMany("Consultas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PrevisaoDoTempoAPI.Models.Usuario", b =>
                {
                    b.Navigation("Chaves");

                    b.Navigation("Consultas");
                });
#pragma warning restore 612, 618
        }
    }
}
